'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('#header'),menu=$('.menu'),nav=$('#nav'),topBtn=$('#top');
const timelineData=[
 {date:'Sample Date 01',title:'Archive Item Sample: Planning Context',text:'Placeholder description showing where verified context about an approved historical event could appear.',source:'Source required before publication.'},
 {date:'Sample Date 02',title:'Archive Item Sample: Public Deliberation',text:'Placeholder description for a future account of public discussion, participation or institutional process.',source:'Client-approved citation required.'},
 {date:'Sample Date 03',title:'Archive Item Sample: Constitutional Milestone',text:'Placeholder description reserved for a verified constitutional milestone and its documented significance.',source:'Date and interpretation are not verified.'},
 {date:'Sample Date 04',title:'Archive Item Sample: Community Impact',text:'Placeholder description for future evidence about community experience, public education or civic protection.',source:'Community and archival review required.'},
 {date:'Sample Date 05',title:'Sample Present-Day Reflection',text:'Placeholder description showing how Project74 may connect historical material to present-day civic learning.',source:'Editorial content pending approval.'}
];
const categories=['All','Constitutional Documents','Convention Records','Historical Correspondence','Genealogy','Civil Rights','Educational Resources'];
const archiveData=[
 ['1974 sample','Constitutional Documents','Archive Item Sample: Constitutional Page','A visual placeholder for a future approved constitutional document.'],
 ['Date pending','Convention Records','Archive Item Sample: Convention Record','A sample listing reserved for a verified convention record and contextual note.'],
 ['Year pending','Historical Correspondence','Archive Item Sample: Historical Letter','A placeholder for approved correspondence with provenance and rights information.'],
 ['Date pending','Genealogy','Archive Item Sample: Family Record Index','A sample research entry demonstrating names, places and relationship metadata.'],
 ['Year pending','Civil Rights','Archive Item Sample: Civic Protection Resource','A respectful placeholder for sourced material related to rights and public institutions.'],
 ['Current sample','Educational Resources','Archive Item Sample: Educator Guide','A sample classroom resource card awaiting approved learning content.'],
 ['Year pending','Genealogy','Archive Item Sample: Community Register','A future pathway for community research using verified public records.'],
 ['Date pending','Convention Records','Archive Item Sample: Proceedings Note','A sample interface entry for proceedings, summaries and source citations.']
].map((x,i)=>({year:x[0],category:x[1],title:x[2],description:x[3],image:'./assets/images/archive-sample.svg',id:i}));
let activeCategory='All';
function initNav(){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>20);topBtn.classList.toggle('show',scrollY>650)},{passive:true});topBtn.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}))}
function initReveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){$$('.reveal').forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.13});$$('.reveal').forEach(e=>io.observe(e))}
function initTimeline(){const list=$('#timeline-list');timelineData.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<b>${item.date}</b><span>${item.title.replace('Archive Item Sample: ','')}</span>`;b.addEventListener('click',()=>selectTimeline(i,b));list.append(b)});selectTimeline(0,list.firstElementChild)}
function selectTimeline(i,b){$$('#timeline-list button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tl-title').textContent=timelineData[i].title;$('#tl-text').textContent=timelineData[i].text;$('#tl-source').textContent=timelineData[i].source}
function initArchive(){const filters=$('#filters'),search=$('#archive-search');categories.forEach(c=>{const b=document.createElement('button');b.type='button';b.textContent=c;b.classList.toggle('active',c==='All');b.addEventListener('click',()=>{activeCategory=c;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderArchive()});filters.append(b)});search.addEventListener('input',renderArchive);renderArchive();$$('[data-filter-link]').forEach(a=>a.addEventListener('click',()=>{activeCategory=a.dataset.filterLink;setTimeout(()=>{const btn=$$('#filters button').find(x=>x.textContent===activeCategory);if(btn){$$('#filters button').forEach(x=>x.classList.toggle('active',x===btn));renderArchive()}},50)}))}
function renderArchive(){const grid=$('#archive-grid'),q=$('#archive-search').value.trim().toLowerCase();const items=archiveData.filter(x=>(activeCategory==='All'||x.category===activeCategory)&&`${x.year} ${x.category} ${x.title} ${x.description}`.toLowerCase().includes(q));grid.innerHTML='';items.forEach(item=>{const a=document.createElement('article');a.className='archive-card';a.innerHTML=`<img src="${item.image}" alt="Decorative placeholder for ${item.title}" loading="lazy" width="800" height="600"><div><small>${item.category} · ${item.year}</small><h3>${item.title}</h3><p>${item.description}</p><button type="button">View Document →</button></div>`;a.querySelector('button').addEventListener('click',()=>openDialog(item));grid.append(a)});$('#results').textContent=`${items.length} sample item${items.length===1?'':'s'} shown`;$('#empty').hidden=items.length!==0}
function openDialog(item){const d=$('#archive-dialog');$('#dialog-title').textContent=item.title;$('#dialog-meta').textContent=`${item.category} · ${item.year} · Sample content`;d.showModal();$('.close',d).focus()}
function initDialog(){const d=$('#archive-dialog');$('.close',d).addEventListener('click',()=>d.close());$('.close2',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()})}
function initForm(){const f=$('#contact-form'),status=$('#form-status'),CONTACT_EMAIL='hello@project74.example';f.addEventListener('submit',e=>{e.preventDefault();if(!f.checkValidity()){status.textContent='Please complete every required field with a valid email address.';f.reportValidity();return}const data=new FormData(f),subject=encodeURIComponent(`[Project74] ${data.get('subject')}`),body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`);status.textContent='Opening your email application. No information is stored by this website.';location.href=`mailto:${CONTACT_EMAIL}?subject=${subject}&body=${body}`})}
function initFooter(){$('#year').textContent=new Date().getFullYear();$$('[data-disclosure]').forEach(b=>b.addEventListener('click',()=>{const d=$(`#${b.dataset.disclosure}`);d.open=true;d.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})}));$$('footer a[href="#"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()))}
initNav();initReveal();initTimeline();initArchive();initDialog();initForm();initFooter();
